name: 📊 Generate GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: 📈 Generate Metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Ho_Chi_Minh
          plugin_languages: yes
          plugin_stargazers: yes
          plugin_traffic: yes
